version: '3.9'
services:
  reactions:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ".:/opt/reactions"
      - "/opt/reactions/node_modules"
    environment:
      - NEXT_WEBPACK_USEPOLLING=true
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    